server:
    port: 8899
    servlet:
        context-path: /am
spring:
    data:
        mongodb:
            host: 209.58.164.25
            port: 27017
            database: system_am
            username: application
            password: b4dpwpr0v1d3d
logging:
#    config: classpath:logback-spring.xml
#    file: C:/u01/apps/AM/log/init.log
    file: /opt/account-management/log/init.log